-- VHDL Entity ece411.BTB_Way.symbol
--
-- Created:
--          by - one1.ews (siebl-0224-30.ews.illinois.edu)
--          at - 20:24:02 04/16/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY BTB_Way IS
   PORT( 
      DataIn     : IN     btb_line;
      DataWrite  : IN     std_logic;
      RESET_L    : IN     std_logic;
      ReadIndex  : IN     lc3b_c_index;
      ReadTag    : IN     std_logic_vector (12 DOWNTO 0);
      WriteIndex : IN     LC3b_c_index;
      WriteTag   : IN     std_logic_vector (12 DOWNTO 0);
      DataOut    : OUT    btb_line;
      Present    : OUT    std_logic
   );

-- Declarations

END BTB_Way ;

--
-- VHDL Architecture ece411.BTB_Way.struct
--
-- Created:
--          by - one1.ews (siebl-0224-30.ews.illinois.edu)
--          at - 20:24:02 04/16/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF BTB_Way IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL CompVal : std_logic;
   SIGNAL Tag     : std_logic_vector(12 DOWNTO 0);
   SIGNAL Valid   : std_logic;


   -- Component Declarations
   COMPONENT AND2
   PORT (
      A : IN     std_logic ;
      B : IN     std_logic ;
      Y : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT BTB_Line_Array
   PORT (
      RESET_L    : IN     std_logic ;
      DataWrite  : IN     std_logic ;
      ReadIndex  : IN     LC3b_c_index ;
      WriteIndex : IN     LC3b_c_index ;
      DataIn     : IN     btb_line ;
      DataOut    : OUT    btb_line 
   );
   END COMPONENT;
   COMPONENT Bit_Array_RW
   PORT (
      RESET_L    : IN     std_logic ;
      DataWrite  : IN     std_logic ;
      ReadIndex  : IN     LC3b_c_index ;
      WriteIndex : IN     LC3b_c_index ;
      DataIn     : IN     std_logic ;
      DataOut    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Comparator
   GENERIC (
      N     : Integer;
      Delay : time
   );
   PORT (
      A : IN     std_logic_vector (N-1 DOWNTO 0);
      B : IN     std_logic_vector (N-1 DOWNTO 0);
      Y : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT Data_Array_RW
   GENERIC (
      N : Integer
   );
   PORT (
      RESET_L    : IN     std_logic ;
      DataWrite  : IN     std_logic ;
      ReadIndex  : IN     LC3b_c_index ;
      WriteIndex : IN     LC3b_c_index ;
      DataIn     : IN     std_logic_vector (N-1 DOWNTO 0);
      DataOut    : OUT    std_logic_vector (N-1 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AND2 USE ENTITY ece411.AND2;
   FOR ALL : BTB_Line_Array USE ENTITY ece411.BTB_Line_Array;
   FOR ALL : Bit_Array_RW USE ENTITY ece411.Bit_Array_RW;
   FOR ALL : Comparator USE ENTITY ece411.Comparator;
   FOR ALL : Data_Array_RW USE ENTITY ece411.Data_Array_RW;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : AND2
      PORT MAP (
         A => CompVal,
         B => Valid,
         Y => Present
      );
   BTBArray : BTB_Line_Array
      PORT MAP (
         RESET_L    => RESET_L,
         DataWrite  => DataWrite,
         ReadIndex  => ReadIndex,
         WriteIndex => WriteIndex,
         DataIn     => DataIn,
         DataOut    => DataOut
      );
   ValidArray : Bit_Array_RW
      PORT MAP (
         RESET_L    => RESET_L,
         DataWrite  => DataWrite,
         ReadIndex  => ReadIndex,
         WriteIndex => WriteIndex,
         DataIn     => DataWrite,
         DataOut    => Valid
      );
   TagCompare : Comparator
      GENERIC MAP (
         N     => 13,
         Delay => DELAY_COMPARE16
      )
      PORT MAP (
         A => Tag,
         B => ReadTag,
         Y => CompVal
      );
   TagArray : Data_Array_RW
      GENERIC MAP (
         N => 13
      )
      PORT MAP (
         RESET_L    => RESET_L,
         DataWrite  => DataWrite,
         ReadIndex  => ReadIndex,
         WriteIndex => WriteIndex,
         DataIn     => WriteTag,
         DataOut    => Tag
      );

END struct;
