-- VHDL Entity ece411.bubbleUnit.interface
--
-- Created:
--          by - goldste6.ews (gelib-057-18.ews.illinois.edu)
--          at - 00:22:47 04/13/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY bubbleUnit IS
   PORT( 
      CLK                   : IN     std_logic;
      decode_flush          : IN     std_logic;
      exec_flush            : IN     std_logic;
      mem_flush             : IN     std_logic;
      stall_load_use_buffer : IN     std_logic;
      uarch_flush           : IN     std_logic;
      decode_insert_bubble  : OUT    std_logic;
      exec_insert_bubble    : OUT    std_logic;
      mem_insert_bubble     : OUT    std_logic;
      uarch_insert_bubble   : OUT    std_logic
   );

-- Declarations

END bubbleUnit ;

--
-- VHDL Architecture ece411.bubbleUnit.struct
--
-- Created:
--          by - goldste6.ews (gelib-057-18.ews.illinois.edu)
--          at - 00:22:47 04/13/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY mp3lib;

ARCHITECTURE struct OF bubbleUnit IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT OR2
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : OR2 USE ENTITY mp3lib.OR2;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 4 eb4
   decode_insert_bubble <= decode_flush;
   mem_insert_bubble    <= mem_flush;
   uarch_insert_bubble  <= uarch_flush;


   -- Instance port mappings.
   U_0 : OR2
      PORT MAP (
         A => exec_flush,
         B => stall_load_use_buffer,
         F => exec_insert_bubble
      );

END struct;
