-- VHDL Entity ece411.decodeStage.interface
--
-- Created:
--          by - wheele11.ews (gelib-057-06.ews.illinois.edu)
--          at - 19:31:29 03/09/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY decodeStage IS
   PORT( 
      CLK               : IN     std_logic;
      RESET_L           : IN     STD_LOGIC;
      decode_instr      : IN     LC3b_word;
      decode_pc         : IN     LC3b_word;
      wb_dest           : IN     LC3B_REG;
      wb_din            : IN     LC3B_WORD;
      wb_regwrite       : IN     STD_LOGIC;
      decode_alumux_sel : OUT    STD_LOGIC_VECTOR (1 DOWNTO 0);
      decode_aluop      : OUT    LC3b_aluop;
      decode_dr         : OUT    LC3B_REG;
      decode_opcode     : OUT    LC3b_opcode;
      decode_ready      : OUT    std_logic;
      decode_regwrite   : OUT    std_logic;
      decode_shift_imm  : OUT    STD_LOGIC;
      decode_src_a      : OUT    LC3b_word;
      decode_src_b      : OUT    LC3b_word
   );

-- Declarations

END decodeStage ;

--
-- VHDL Architecture ece411.decodeStage.struct
--
-- Created:
--          by - wheele11.ews (gelib-057-06.ews.illinois.edu)
--          at - 19:31:29 03/09/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;
LIBRARY mp3lib;

ARCHITECTURE struct OF decodeStage IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL F              : STD_LOGIC;
   SIGNAL F1             : STD_LOGIC;
   SIGNAL F10            : STD_LOGIC;
   SIGNAL F11            : STD_LOGIC;
   SIGNAL F12            : STD_LOGIC;
   SIGNAL F13            : STD_LOGIC;
   SIGNAL F14            : STD_LOGIC;
   SIGNAL F15            : STD_LOGIC;
   SIGNAL F16            : STD_LOGIC;
   SIGNAL F17            : STD_LOGIC;
   SIGNAL F19            : STD_LOGIC;
   SIGNAL F5             : STD_LOGIC;
   SIGNAL F6             : STD_LOGIC;
   SIGNAL F7             : STD_LOGIC;
   SIGNAL F8             : STD_LOGIC;
   SIGNAL F9             : STD_LOGIC;
   SIGNAL R7             : STD_LOGIC_VECTOR(2 DOWNTO 0);
   SIGNAL SrcA           : STD_LOGIC_VECTOR(2 DOWNTO 0);
   SIGNAL SrcAMuxOut     : STD_LOGIC_VECTOR(2 DOWNTO 0);
   SIGNAL SrcAMuxSel     : STD_LOGIC;
   SIGNAL SrcB           : LC3B_REG;
   SIGNAL bit11          : std_logic;
   SIGNAL bit5           : std_logic;
   SIGNAL decode_use_imm : STD_LOGIC;
   SIGNAL direction      : std_logic;
   SIGNAL imm4           : LC3b_imm4;
   SIGNAL imm5           : LC3b_imm5;
   SIGNAL index6         : LC3b_index6;
   SIGNAL instr          : LC3b_word;
   SIGNAL is_imm4        : STD_LOGIC;
   SIGNAL is_imm5        : STD_LOGIC;
   SIGNAL is_off6        : STD_LOGIC;
   SIGNAL is_sla         : STD_LOGIC;
   SIGNAL is_sra         : STD_LOGIC;
   SIGNAL offset11       : LC3b_offset11;
   SIGNAL offset9        : LC3b_offset9;
   SIGNAL op_add         : STD_LOGIC;
   SIGNAL op_and         : STD_LOGIC;
   SIGNAL op_br          : STD_LOGIC;
   SIGNAL op_jsr         : STD_LOGIC;
   SIGNAL op_ldb         : STD_LOGIC;
   SIGNAL op_ldi         : STD_LOGIC;
   SIGNAL op_ldr         : STD_LOGIC;
   SIGNAL op_lea         : STD_LOGIC;
   SIGNAL op_not         : STD_LOGIC;
   SIGNAL op_ret         : STD_LOGIC;
   SIGNAL op_shf         : STD_LOGIC;
   SIGNAL op_stb         : STD_LOGIC;
   SIGNAL op_sti         : STD_LOGIC;
   SIGNAL op_str         : STD_LOGIC;
   SIGNAL op_trap        : STD_LOGIC;
   SIGNAL trapvec8       : LC3b_trapvect8;

   -- Implicit buffer signal declarations
   SIGNAL decode_opcode_internal : LC3b_opcode;


   -- Component Declarations
   COMPONENT Dec4_16
   PORT (
      A : IN     STD_LOGIC_VECTOR (3 DOWNTO 0);
      F : OUT    STD_LOGIC_VECTOR (15 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT ID
   PORT (
      decode_instr : IN     LC3b_word ;
      Opcode       : OUT    LC3b_opcode ;
      SrcA         : OUT    LC3b_reg ;
      SrcB         : OUT    LC3b_reg ;
      dest         : OUT    LC3b_reg ;
      index6       : OUT    LC3b_index6 ;
      imm5         : OUT    LC3b_imm5 ;
      bit5         : OUT    std_logic ;
      offset9      : OUT    LC3b_offset9 ;
      trapvec8     : OUT    LC3b_trapvect8 ;
      offset11     : OUT    LC3b_offset11 ;
      bit11        : OUT    std_logic ;
      imm4         : OUT    LC3b_imm4 ;
      direction    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT AND2
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT MUX2_3
   PORT (
      A   : IN     STD_LOGIC_VECTOR (2 DOWNTO 0);
      B   : IN     STD_LOGIC_VECTOR (2 DOWNTO 0);
      SEL : IN     STD_LOGIC ;
      F   : OUT    STD_LOGIC_VECTOR (2 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT NAND2
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT NOT1
   PORT (
      A : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT OR2
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT OR3
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      C : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT REGFILE
   PORT (
      CLK      : IN     STD_LOGIC ;
      DEST     : IN     LC3B_REG ;
      DIN      : IN     LC3B_WORD ;
      RESET_L  : IN     STD_LOGIC ;
      REGWRITE : IN     STD_LOGIC ;
      SRCA     : IN     LC3B_REG ;
      SRCB     : IN     LC3B_REG ;
      A        : OUT    LC3B_WORD ;
      B        : OUT    LC3B_WORD 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AND2 USE ENTITY mp3lib.AND2;
   FOR ALL : Dec4_16 USE ENTITY ece411.Dec4_16;
   FOR ALL : ID USE ENTITY ece411.ID;
   FOR ALL : MUX2_3 USE ENTITY mp3lib.MUX2_3;
   FOR ALL : NAND2 USE ENTITY mp3lib.NAND2;
   FOR ALL : NOT1 USE ENTITY mp3lib.NOT1;
   FOR ALL : OR2 USE ENTITY mp3lib.OR2;
   FOR ALL : OR3 USE ENTITY mp3lib.OR3;
   FOR ALL : REGFILE USE ENTITY mp3lib.REGFILE;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   op_br   <= instr(0);
   op_add  <= instr(1);
   op_ldb  <= instr(2);
   op_stb  <= instr(3);
   op_jsr  <= instr(4);
   op_and  <= instr(5);
   op_ldr  <= instr(6);
   op_str  <= instr(7);
   -- op_rti
   op_not  <= instr(9);
   op_ldi  <= instr(10);
   op_sti  <= instr(11);
   op_ret  <= instr(12);
   op_shf  <= instr(13);
   op_lea  <= instr(14);
   op_trap <= instr(15);

   -- HDL Embedded Text Block 2 eb2
   SrcAMuxSel <= op_jsr;
   R7 <= "111";

   -- HDL Embedded Text Block 3 eb3
   -- External API
   decode_ready <= '1';

   -- HDL Embedded Text Block 4 eb4
   decode_aluop(2) <= op_shf;

   -- HDL Embedded Text Block 5 eb5
   is_imm4 <= op_shf;


   -- Instance port mappings.
   opcodeDecoder : Dec4_16
      PORT MAP (
         A => decode_opcode_internal,
         F => instr
      );
   IDUnit : ID
      PORT MAP (
         decode_instr => decode_instr,
         Opcode       => decode_opcode_internal,
         SrcA         => SrcA,
         SrcB         => SrcB,
         dest         => decode_dr,
         index6       => index6,
         imm5         => imm5,
         bit5         => bit5,
         offset9      => offset9,
         trapvec8     => trapvec8,
         offset11     => offset11,
         bit11        => bit11,
         imm4         => imm4,
         direction    => direction
      );
   U_2 : AND2
      PORT MAP (
         A => F,
         B => decode_instr(13),
         F => is_off6
      );
   U_9 : AND2
      PORT MAP (
         A => op_jsr,
         B => bit11,
         F => F5
      );
   U_11 : AND2
      PORT MAP (
         A => F7,
         B => bit5,
         F => F6
      );
   U_15 : AND2
      PORT MAP (
         A => F9,
         B => F11,
         F => F10
      );
   U_20 : AND2
      PORT MAP (
         A => decode_instr(4),
         B => decode_instr(5),
         F => F17
      );
   U_21 : AND2
      PORT MAP (
         A => F16,
         B => op_shf,
         F => is_sla
      );
   U_23 : AND2
      PORT MAP (
         A => F17,
         B => op_shf,
         F => is_sra
      );
   U_25 : AND2
      PORT MAP (
         A => op_shf,
         B => decode_instr(4),
         F => F14
      );
   U_29 : AND2
      PORT MAP (
         A => op_and,
         B => decode_instr(5),
         F => F15
      );
   U_30 : AND2
      PORT MAP (
         A => decode_instr(5),
         B => op_add,
         F => F19
      );
   U_0 : MUX2_3
      PORT MAP (
         A   => SrcA,
         B   => R7,
         SEL => SrcAMuxSel,
         F   => SrcAMuxOut
      );
   U_3 : NAND2
      PORT MAP (
         A => decode_instr(15),
         B => decode_instr(14),
         F => F
      );
   U_16 : NAND2
      PORT MAP (
         A => F12,
         B => decode_opcode_internal(0),
         F => F11
      );
   U_5 : NOT1
      PORT MAP (
         A => decode_instr(13),
         F => F1
      );
   U_17 : NOT1
      PORT MAP (
         A => decode_opcode_internal(1),
         F => F12
      );
   U_22 : NOT1
      PORT MAP (
         A => decode_instr(4),
         F => F16
      );
   U_10 : OR2
      PORT MAP (
         A => F5,
         B => F6,
         F => F8
      );
   U_12 : OR2
      PORT MAP (
         A => op_and,
         B => op_add,
         F => F7
      );
   U_13 : OR2
      PORT MAP (
         A => F8,
         B => F10,
         F => decode_use_imm
      );
   U_14 : OR2
      PORT MAP (
         A => decode_opcode_internal(3),
         B => decode_opcode_internal(2),
         F => F9
      );
   U_18 : OR2
      PORT MAP (
         A => op_and,
         B => F13,
         F => decode_aluop(0)
      );
   U_19 : OR2
      PORT MAP (
         A => is_sla,
         B => is_sra,
         F => F13
      );
   U_24 : OR2
      PORT MAP (
         A => op_not,
         B => F14,
         F => decode_aluop(1)
      );
   U_26 : OR2
      PORT MAP (
         A => is_imm4,
         B => is_off6,
         F => decode_alumux_sel(0)
      );
   U_27 : OR2
      PORT MAP (
         A => is_imm5,
         B => is_off6,
         F => decode_alumux_sel(1)
      );
   U_28 : OR2
      PORT MAP (
         A => F15,
         B => F19,
         F => is_imm5
      );
   U_1 : OR3
      PORT MAP (
         A => op_and,
         B => op_add,
         C => op_not,
         F => decode_regwrite
      );
   U_4 : OR3
      PORT MAP (
         A => F1,
         B => decode_instr(14),
         C => decode_instr(15),
         F => decode_shift_imm
      );
   aRF : REGFILE
      PORT MAP (
         CLK      => CLK,
         DEST     => wb_dest,
         DIN      => wb_din,
         RESET_L  => RESET_L,
         REGWRITE => wb_regwrite,
         SRCA     => SrcAMuxOut,
         SRCB     => SrcB,
         A        => decode_src_a,
         B        => decode_src_b
      );

   -- Implicit buffered output assignments
   decode_opcode <= decode_opcode_internal;

END struct;
