-- VHDL Entity ece411.Encoder_4_2.symbol
--
-- Created:
--          by - one1.ews (gelib-057-06.ews.illinois.edu)
--          at - 21:14:40 04/19/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Encoder_4_2 IS
   PORT( 
      A  : IN     std_logic;
      B  : IN     std_logic;
      C  : IN     std_logic;
      D  : IN     std_logic;
      F0 : OUT    std_logic;
      F1 : OUT    std_logic
   );

-- Declarations

END Encoder_4_2 ;

--
-- VHDL Architecture ece411.Encoder_4_2.struct
--
-- Created:
--          by - one1.ews (gelib-057-06.ews.illinois.edu)
--          at - 21:14:40 04/19/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY mp3lib;

ARCHITECTURE struct OF Encoder_4_2 IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT OR2
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : OR2 USE ENTITY mp3lib.OR2;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : OR2
      PORT MAP (
         A => D,
         B => C,
         F => F1
      );
   U_1 : OR2
      PORT MAP (
         A => B,
         B => D,
         F => F0
      );

END struct;
