-- VHDL Entity ece411.exec_mem_pipe.interface
--
-- Created:
--          by - goldste6.ews (gelib-057-18.ews.illinois.edu)
--          at - 23:42:43 04/12/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY exec_mem_pipe IS
   PORT( 
      CLK                : IN     std_logic;
      RESET_L            : IN     STD_LOGIC;
      exec_control       : IN     control_word;
      exec_data_out      : IN     pipe_data;
      load_exec_mem_pipe : IN     STD_LOGIC;
      mem_insert_bubble  : IN     std_logic;
      mem_control        : OUT    control_word;
      mem_control_in     : OUT    mem_control_word;
      mem_data_in        : OUT    pipe_data;
      wb_control_in      : OUT    wb_control_word
   );

-- Declarations

END exec_mem_pipe ;

--
-- VHDL Architecture ece411.exec_mem_pipe.struct
--
-- Created:
--          by - goldste6.ews (gelib-057-18.ews.illinois.edu)
--          at - 23:42:43 04/12/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF exec_mem_pipe IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL mem_control_buffer : control_word;


   -- Component Declarations
   COMPONENT RegControl
   PORT (
      RESET_L : IN     STD_LOGIC ;
      A       : IN     control_word ;
      EN      : IN     STD_LOGIC ;
      CLK     : IN     std_logic ;
      F       : OUT    control_word 
   );
   END COMPONENT;
   COMPONENT RegData
   PORT (
      RESET_L : IN     STD_LOGIC ;
      A       : IN     pipe_data ;
      EN      : IN     STD_LOGIC ;
      CLK     : IN     std_logic ;
      F       : OUT    pipe_data 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : RegControl USE ENTITY ece411.RegControl;
   FOR ALL : RegData USE ENTITY ece411.RegData;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   mem_control <= mem_control_buffer;
   mem_control_in <= mem_control_buffer.mem;
   wb_control_in  <= mem_control_buffer.wb;


   -- Instance port mappings.
   U_6 : RegControl
      PORT MAP (
         RESET_L => RESET_L,
         A       => exec_control,
         EN      => load_exec_mem_pipe,
         CLK     => CLK,
         F       => mem_control_buffer
      );
   aRegData1 : RegData
      PORT MAP (
         RESET_L => RESET_L,
         A       => exec_data_out,
         EN      => load_exec_mem_pipe,
         CLK     => CLK,
         F       => mem_data_in
      );

END struct;
