-- VHDL Entity ece411.fetch_decode_pipe.interface
--
-- Created:
--          by - wheele11.ews (gelib-057-07.ews.illinois.edu)
--          at - 03:12:09 03/09/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY fetch_decode_pipe IS
   PORT( 
      CLK          : IN     std_logic;
      RESET_L      : IN     STD_LOGIC;
      fetch_instr  : IN     LC3b_word;
      fetch_ready  : IN     std_logic;
      pc           : IN     LC3b_word;
      decode_instr : OUT    LC3b_word;
      decode_pc    : OUT    LC3b_word
   );

-- Declarations

END fetch_decode_pipe ;

--
-- VHDL Architecture ece411.fetch_decode_pipe.struct
--
-- Created:
--          by - wheele11.ews (gelib-057-07.ews.illinois.edu)
--          at - 03:12:09 03/09/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY mp3lib;

ARCHITECTURE struct OF fetch_decode_pipe IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT REG16
   PORT (
      RESET_L : IN     STD_LOGIC ;
      A       : IN     STD_LOGIC_VECTOR (15 DOWNTO 0);
      EN      : IN     STD_LOGIC ;
      CLK     : IN     STD_LOGIC ;
      F       : OUT    STD_LOGIC_VECTOR (15 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : REG16 USE ENTITY mp3lib.REG16;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : REG16
      PORT MAP (
         RESET_L => RESET_L,
         A       => pc,
         EN      => fetch_ready,
         CLK     => CLK,
         F       => decode_pc
      );
   U_1 : REG16
      PORT MAP (
         RESET_L => RESET_L,
         A       => fetch_instr,
         EN      => fetch_ready,
         CLK     => CLK,
         F       => decode_instr
      );

END struct;
