-- VHDL Entity ece411.Fix_pmresp_h.generatedInstance
--
-- Created:
--          by - wheele11.ews (gelib-057-20.ews.illinois.edu)
--          at - 21:12:19 04/15/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Fix_pmresp_h IS
   PORT( 
      PMRESP_H       : IN     std_logic;
      FIXED_PMRESP_H : OUT    STD_LOGIC
   );

END Fix_pmresp_h ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Fix_pmresp_h IS 
BEGIN


END generatedInstance;
