-- VHDL Entity ece411.L1Cache.symbol
--
-- Created:
--          by - goldste6.ews (linux6.ews.illinois.edu)
--          at - 23:20:32 04/13/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY L1Cache IS
   PORT( 
      ADDRESS   : IN     LC3B_WORD;
      CLK       : IN     std_logic;
      Dataout   : IN     LC3B_WORD;
      MREAD_L   : IN     std_logic;
      MWRITEH_L : IN     std_logic;
      MWRITEL_L : IN     std_logic;
      PMDATAIN  : IN     LC3B_OWORD;
      PMRESP_H  : IN     std_logic;
      RESET_L   : IN     std_logic;
      DATAIN    : OUT    LC3B_WORD;
      MRESP_H   : OUT    std_logic;
      PMADDRESS : OUT    LC3B_WORD;
      PMDATAOUT : OUT    LC3B_OWORD;
      PMREAD_L  : OUT    std_logic;
      PMWRITE_L : OUT    std_logic
   );

-- Declarations

END L1Cache ;

--
-- VHDL Architecture ece411.L1Cache.struct
--
-- Created:
--          by - goldste6.ews (linux6.ews.illinois.edu)
--          at - 23:20:32 04/13/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF L1Cache IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL evict_buffer_valid : std_logic;
   SIGNAL in_idlehit         : std_logic;
   SIGNAL in_load            : std_logic;
   SIGNAL in_writeback       : std_logic;
   SIGNAL miss               : std_logic;


   -- Component Declarations
   COMPONENT Cache_Controller
   PORT (
      CLK                : IN     std_logic ;
      PMRESP_H           : IN     STD_LOGIC ;
      RESET_L            : IN     STD_LOGIC ;
      evict_buffer_valid : IN     std_logic ;
      miss               : IN     std_logic ;
      PMREAD_L           : OUT    STD_LOGIC ;
      PMWRITE_L          : OUT    STD_LOGIC ;
      in_idlehit         : OUT    std_logic ;
      in_load            : OUT    std_logic ;
      in_writeback       : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Cache_Datapath
   PORT (
      Address            : IN     LC3b_word ;
      Dataout            : IN     LC3b_word ;
      MREAD_L            : IN     std_logic ;
      MWRITEH_L          : IN     std_logic ;
      MWRITEL_L          : IN     std_logic ;
      PMDATAIN           : IN     LC3B_OWORD ;
      PMRESP_H           : IN     STD_LOGIC ;
      clk                : IN     std_logic ;
      in_idlehit         : IN     std_logic ;
      in_load            : IN     std_logic ;
      in_writeback       : IN     std_logic ;
      reset_l            : IN     STD_LOGIC ;
      DATAIN             : OUT    LC3b_word ;
      MRESP_H            : OUT    std_logic ;
      PMADDRESS          : OUT    LC3B_WORD ;
      PMDATAOUT          : OUT    LC3B_OWORD ;
      evict_buffer_valid : OUT    std_logic ;
      miss               : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Cache_Controller USE ENTITY ece411.Cache_Controller;
   FOR ALL : Cache_Datapath USE ENTITY ece411.Cache_Datapath;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   Cache_Cont : Cache_Controller
      PORT MAP (
         CLK                => CLK,
         PMRESP_H           => PMRESP_H,
         RESET_L            => RESET_L,
         evict_buffer_valid => evict_buffer_valid,
         miss               => miss,
         PMREAD_L           => PMREAD_L,
         PMWRITE_L          => PMWRITE_L,
         in_idlehit         => in_idlehit,
         in_load            => in_load,
         in_writeback       => in_writeback
      );
   Cache_DP1 : Cache_Datapath
      PORT MAP (
         Address            => ADDRESS,
         Dataout            => Dataout,
         MREAD_L            => MREAD_L,
         MWRITEH_L          => MWRITEH_L,
         MWRITEL_L          => MWRITEL_L,
         PMDATAIN           => PMDATAIN,
         PMRESP_H           => PMRESP_H,
         clk                => CLK,
         in_idlehit         => in_idlehit,
         in_load            => in_load,
         in_writeback       => in_writeback,
         reset_l            => RESET_L,
         DATAIN             => DATAIN,
         MRESP_H            => MRESP_H,
         PMADDRESS          => PMADDRESS,
         PMDATAOUT          => PMDATAOUT,
         evict_buffer_valid => evict_buffer_valid,
         miss               => miss
      );

END struct;
