-- VHDL Entity ece411.L1Way.symbol
--
-- Created:
--          by - goldste6.ews (gelib-057-33.ews.illinois.edu)
--          at - 22:59:58 04/25/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY L1Way IS
   PORT( 
      DataWrite  : IN     std_logic;
      RESET_L    : IN     std_logic;
      ReadIndex  : IN     lc3b_c_index;
      Set_Dirty  : IN     std_logic;
      WayDataIn  : IN     LC3b_OWORD;
      WriteIndex : IN     LC3b_c_index;
      WriteTag   : IN     LC3b_c_tag;
      Dirty      : OUT    std_logic;
      TagOut     : OUT    LC3b_C_TAG;
      Valid      : OUT    std_logic;
      WayDataout : OUT    LC3B_OWORD
   );

-- Declarations

END L1Way ;

--
-- VHDL Architecture ece411.L1Way.struct
--
-- Created:
--          by - goldste6.ews (gelib-057-33.ews.illinois.edu)
--          at - 22:59:58 04/25/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF L1Way IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT Bit_Array_RW
   GENERIC (
      Delay : Time
   );
   PORT (
      DataIn     : IN     std_logic;
      DataWrite  : IN     std_logic;
      RESET_L    : IN     std_logic;
      ReadIndex  : IN     LC3b_C_INDEX;
      WriteIndex : IN     LC3B_C_INDEX;
      DataOut    : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT Data_Array_RW
   GENERIC (
      N     : Integer;
      Delay : Time
   );
   PORT (
      DataIn     : IN     std_logic_vector (N-1 DOWNTO 0);
      DataWrite  : IN     std_logic;
      RESET_L    : IN     std_logic;
      ReadIndex  : IN     LC3B_C_INDEX;
      WriteIndex : IN     LC3B_C_INDEX;
      DataOut    : OUT    std_logic_vector (N-1 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Bit_Array_RW USE ENTITY ece411.Bit_Array_RW;
   FOR ALL : Data_Array_RW USE ENTITY ece411.Data_Array_RW;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   DirtyBits : Bit_Array_RW
      GENERIC MAP (
         Delay => DELAY_256B
      )
      PORT MAP (
         RESET_L    => RESET_L,
         DataWrite  => DataWrite,
         ReadIndex  => ReadIndex,
         WriteIndex => WriteIndex,
         DataIn     => Set_Dirty,
         DataOut    => Dirty
      );
   ValidBits : Bit_Array_RW
      GENERIC MAP (
         Delay => DELAY_256B
      )
      PORT MAP (
         RESET_L    => RESET_L,
         DataWrite  => DataWrite,
         ReadIndex  => ReadIndex,
         WriteIndex => WriteIndex,
         DataIn     => DataWrite,
         DataOut    => Valid
      );
   TagBits : Data_Array_RW
      GENERIC MAP (
         N     => 9,
         Delay => DELAY_256B
      )
      PORT MAP (
         RESET_L    => RESET_L,
         DataWrite  => DataWrite,
         ReadIndex  => ReadIndex,
         WriteIndex => WriteIndex,
         DataIn     => WriteTag,
         DataOut    => TagOut
      );
   WayData : Data_Array_RW
      GENERIC MAP (
         N     => 128,
         Delay => DELAY_256B
      )
      PORT MAP (
         RESET_L    => RESET_L,
         DataWrite  => DataWrite,
         ReadIndex  => ReadIndex,
         WriteIndex => WriteIndex,
         DataIn     => WayDataIn,
         DataOut    => WayDataout
      );

END struct;
