-- VHDL Entity ece411.memStage1.interface
--
-- Created:
--          by - one1.ews (gelib-057-16.ews.illinois.edu)
--          at - 18:21:21 04/26/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY memStage1 IS
   PORT( 
      CLK                       : IN     std_logic;
      RESET_L                   : IN     STD_LOGIC;
      dcache_feedback           : IN     LC3b_cache_feedback_data;
      mem1_control_in           : IN     mem_control_word;
      mem1_data_in              : IN     pipe_data;
      dcache_ReadIndex          : OUT    LC3b_C_INDEX;
      dcache_interstage_data_in : OUT    LC3b_cache_interstage_data;
      mem1_cc                   : OUT    LC3b_CC;
      mem1_data_out             : OUT    pipe_data
   );

-- Declarations

END memStage1 ;

--
-- VHDL Architecture ece411.memStage1.struct
--
-- Created:
--          by - one1.ews (gelib-057-16.ews.illinois.edu)
--          at - 18:21:22 04/26/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF memStage1 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL aluout      : LC3B_WORD;
   SIGNAL btb_data    : btb_line;
   SIGNAL cc          : LC3B_cc;
   SIGNAL data_addr   : LC3B_WORD;
   SIGNAL dr          : lc3b_reg;
   SIGNAL dr_val      : lc3b_word;
   SIGNAL idx6        : LC3B_INDEX6;
   SIGNAL imm4        : LC3B_IMM4;
   SIGNAL imm5        : LC3B_IMM5;
   SIGNAL incr_pc     : lc3b_word;
   SIGNAL instr       : lc3b_word;
   SIGNAL mem1_pc     : lc3b_word;
   SIGNAL mem_data_in : lc3b_word;
   SIGNAL nzp         : LC3B_cc;
   SIGNAL off11       : LC3B_OFFSET11;
   SIGNAL off9        : LC3B_OFFSET9;
   SIGNAL sr1         : lc3b_reg;
   SIGNAL sr1_val     : lc3b_word;
   SIGNAL sr2         : lc3b_reg;
   SIGNAL sr2_val     : lc3b_word;
   SIGNAL taken       : std_logic;
   SIGNAL target_pc   : lc3b_word;
   SIGNAL trapvect8   : LC3B_TRAPVECT8;
   SIGNAL wb_data     : lc3b_word;

   -- Implicit buffer signal declarations
   SIGNAL dcache_ReadIndex_internal : LC3b_C_INDEX;


   -- Component Declarations
   COMPONENT GenCC
   PORT (
      WordIn : IN     LC3b_word ;
      nzp    : OUT    LC3b_cc 
   );
   END COMPONENT;
   COMPONENT PipeDataCombiner
   PORT (
      pc          : IN     lc3b_word ;
      incr_pc     : IN     lc3b_word ;
      instr       : IN     lc3b_word ;
      aluout      : IN     lc3b_word ;
      dr          : IN     LC3b_reg ;
      dr_val      : IN     lc3b_word ;
      idx6        : IN     LC3B_INDEX6 ;
      imm4        : IN     LC3b_imm4 ;
      imm5        : IN     LC3b_imm5 ;
      mem_data_in : IN     lc3b_word ;
      data_addr   : IN     lc3b_word ;
      off11       : IN     LC3B_OFFSET11 ;
      off9        : IN     LC3B_OFFSET9 ;
      sr1         : IN     LC3b_reg ;
      sr2         : IN     LC3b_reg ;
      sr1_val     : IN     lc3b_word ;
      sr2_val     : IN     lc3b_word ;
      trapvect8   : IN     lc3b_trapvect8 ;
      nzp         : IN     lc3b_cc ;
      cc          : IN     lc3b_cc ;
      target_pc   : IN     lc3b_word ;
      taken       : IN     std_logic ;
      btb_data    : IN     btb_line ;
      wb_data     : IN     lc3b_word ;
      data_out    : OUT    pipe_data 
   );
   END COMPONENT;
   COMPONENT PipeDataSplitter
   PORT (
      data_in     : IN     pipe_data ;
      pc          : OUT    lc3b_word ;
      incr_pc     : OUT    lc3b_word ;
      instr       : OUT    lc3b_word ;
      aluout      : OUT    lc3b_word ;
      mem_data_in : OUT    lc3b_word ;
      data_addr   : OUT    lc3b_word ;
      sr1         : OUT    lc3b_reg ;
      sr2         : OUT    lc3b_reg ;
      sr1_val     : OUT    lc3b_word ;
      sr2_val     : OUT    lc3b_word ;
      dr_val      : OUT    lc3b_word ;
      dr          : OUT    lc3b_reg ;
      imm4        : OUT    LC3B_IMM4 ;
      imm5        : OUT    LC3B_IMM5 ;
      idx6        : OUT    LC3B_INDEX6 ;
      off9        : OUT    LC3B_OFFSET9 ;
      off11       : OUT    LC3B_OFFSET11 ;
      trapvect8   : OUT    LC3B_TRAPVECT8 ;
      nzp         : OUT    LC3B_cc ;
      cc          : OUT    LC3B_cc ;
      target_pc   : OUT    LC3B_word ;
      taken       : OUT    std_logic ;
      wb_data     : OUT    LC3B_word ;
      btb_data    : OUT    btb_line 
   );
   END COMPONENT;
   COMPONENT Pipelined_L1_Stage1
   PORT (
      ADDRESS         : IN     LC3B_WORD ;
      RESET_L         : IN     std_logic ;
      feedback        : IN     LC3b_cache_feedback_data ;
      interstage_data : OUT    LC3b_cache_interstage_data ;
      ReadIndex       : BUFFER lc3b_c_index 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : GenCC USE ENTITY ece411.GenCC;
   FOR ALL : PipeDataCombiner USE ENTITY ece411.PipeDataCombiner;
   FOR ALL : PipeDataSplitter USE ENTITY ece411.PipeDataSplitter;
   FOR ALL : Pipelined_L1_Stage1 USE ENTITY ece411.Pipelined_L1_Stage1;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   theGenCC : GenCC
      PORT MAP (
         WordIn => aluout,
         nzp    => mem1_cc
      );
   U_14 : PipeDataCombiner
      PORT MAP (
         pc          => mem1_pc,
         incr_pc     => incr_pc,
         instr       => instr,
         aluout      => aluout,
         dr          => dr,
         dr_val      => dr_val,
         idx6        => idx6,
         imm4        => imm4,
         imm5        => imm5,
         mem_data_in => mem_data_in,
         data_addr   => data_addr,
         off11       => off11,
         off9        => off9,
         sr1         => sr1,
         sr2         => sr2,
         sr1_val     => sr1_val,
         sr2_val     => sr2_val,
         trapvect8   => trapvect8,
         nzp         => nzp,
         cc          => cc,
         target_pc   => target_pc,
         taken       => taken,
         btb_data    => btb_data,
         wb_data     => wb_data,
         data_out    => mem1_data_out
      );
   U_13 : PipeDataSplitter
      PORT MAP (
         data_in     => mem1_data_in,
         pc          => mem1_pc,
         incr_pc     => incr_pc,
         instr       => instr,
         aluout      => aluout,
         mem_data_in => mem_data_in,
         data_addr   => data_addr,
         sr1         => sr1,
         sr2         => sr2,
         sr1_val     => sr1_val,
         sr2_val     => sr2_val,
         dr_val      => dr_val,
         dr          => dr,
         imm4        => imm4,
         imm5        => imm5,
         idx6        => idx6,
         off9        => off9,
         off11       => off11,
         trapvect8   => trapvect8,
         nzp         => nzp,
         cc          => cc,
         target_pc   => target_pc,
         taken       => taken,
         wb_data     => wb_data,
         btb_data    => btb_data
      );
   U_0 : Pipelined_L1_Stage1
      PORT MAP (
         ADDRESS         => data_addr,
         RESET_L         => RESET_L,
         feedback        => dcache_feedback,
         interstage_data => dcache_interstage_data_in,
         ReadIndex       => dcache_ReadIndex_internal
      );

   -- Implicit buffered output assignments
   dcache_ReadIndex <= dcache_ReadIndex_internal;

END struct;
