-- VHDL Entity ece411.memStage.interface
--
-- Created:
--          by - goldste6.ews (gelib-057-08.ews.illinois.edu)
--          at - 23:13:10 03/11/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY memStage IS
   PORT( 
      CLK            : IN     std_logic;
      DATAIN         : IN     LC3B_WORD;
      data_resp_h    : IN     std_logic;
      Dataout        : OUT    LC3b_word;
      data_addr      : OUT    LC3b_word;
      data_mread_l   : OUT    std_logic;
      data_mwriteh_l : OUT    std_logic;
      data_mwritel_l : OUT    std_logic;
      mem_ready      : OUT    STD_LOGIC
   );

-- Declarations

END memStage ;

--
-- VHDL Architecture ece411.memStage.struct
--
-- Created:
--          by - goldste6.ews (gelib-057-08.ews.illinois.edu)
--          at - 23:13:10 03/11/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF memStage IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   mem_ready <= '1';
   data_mread_l <= '1';
   data_mwriteh_l <= '1';
   data_mwritel_l <= '1';


   -- Instance port mappings.

END struct;
