-- VHDL Entity ece411.Pipelined_L1_Stage2.symbol
--
-- Created:
--          by - goldste6.ews (siebl-0224-29.ews.illinois.edu)
--          at - 21:53:41 04/16/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Pipelined_L1_Stage2 IS
   PORT( 
      CLK                 : IN     std_logic;
      Dataout             : IN     LC3b_word;
      Index               : IN     LC3b_C_INDEX;
      MREAD_L             : IN     std_logic;
      MWRITEH_L           : IN     std_logic;
      MWRITEL_L           : IN     std_logic;
      Offset              : IN     std_logic_vector (2 DOWNTO 0);
      PMDATAIN            : IN     LC3B_OWORD;
      PMRESP_H            : IN     STD_LOGIC;
      RESET_L             : IN     STD_LOGIC;
      ReadIndex           : IN     LC3b_C_INDEX;
      Tag                 : IN     LC3b_C_TAG;
      Way0Dataout         : IN     LC3B_OWORD;
      Way1Dataout         : IN     LC3B_OWORD;
      dirty0              : IN     std_logic;
      dirty1              : IN     std_logic;
      evicted             : IN     std_logic;
      load_cache_fwd_pipe : IN     std_logic;
      tag0                : IN     LC3b_C_TAG;
      tag1                : IN     LC3b_C_TAG;
      valid0              : IN     std_logic;
      valid1              : IN     std_logic;
      DATAIN              : OUT    LC3b_word;
      MRESP_H             : OUT    std_logic;
      PMADDRESS           : OUT    LC3B_WORD;
      PMDATAOUT           : OUT    LC3B_OWORD;
      PMREAD_L            : OUT    STD_LOGIC;
      PMWRITE_L           : OUT    STD_LOGIC;
      WriteIndex          : OUT    LC3b_C_INDEX;
      WriteTag            : OUT    LC3b_C_TAG;
      WayDataIn           : BUFFER LC3b_OWORD;
      lru_data_in         : BUFFER STD_LOGIC;
      set_dirty           : BUFFER std_logic;
      write0              : BUFFER std_logic;
      write1              : BUFFER std_logic
   );

-- Declarations

END Pipelined_L1_Stage2 ;

--
-- VHDL Architecture ece411.Pipelined_L1_Stage2.struct
--
-- Created:
--          by - goldste6.ews (siebl-0224-29.ews.illinois.edu)
--          at - 21:53:41 04/16/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;
LIBRARY mp3lib;

ARCHITECTURE struct OF Pipelined_L1_Stage2 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL evict_buffer_valid : std_logic;
   SIGNAL in_idlehit         : std_logic;
   SIGNAL in_load            : std_logic;
   SIGNAL in_writeback       : std_logic;
   SIGNAL index_match        : STD_LOGIC;
   SIGNAL last_Set_Dirty     : std_logic;
   SIGNAL last_WayDataIn     : LC3b_OWORD;
   SIGNAL last_WriteTag      : LC3b_c_tag;
   SIGNAL last_lru_data_in   : std_logic;
   SIGNAL last_write0        : std_logic;
   SIGNAL last_write1        : STD_LOGIC;
   SIGNAL miss               : std_logic;
   SIGNAL next_index_match   : std_logic;
   SIGNAL next_replace_way0  : std_logic;
   SIGNAL next_replace_way1  : std_logic;
   SIGNAL replace_way0       : std_logic;
   SIGNAL replace_way1       : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL WriteTag_internal : LC3b_C_TAG;


   -- Component Declarations
   COMPONENT CacheFwdPipe
   PORT (
      CLK                 : IN     std_logic ;
      RESET_L             : IN     STD_LOGIC ;
      WayDataIn           : IN     LC3b_OWORD ;
      WriteTag            : IN     LC3b_C_TAG ;
      load_cache_fwd_pipe : IN     std_logic ;
      lru_data_in         : IN     STD_LOGIC ;
      next_index_match    : IN     std_logic ;
      next_replace_way0   : IN     std_logic ;
      next_replace_way1   : IN     std_logic ;
      set_dirty           : IN     std_logic ;
      write0              : IN     std_logic ;
      write1              : IN     std_logic ;
      index_match         : OUT    STD_LOGIC ;
      last_Set_Dirty      : OUT    std_logic ;
      last_WayDataIn      : OUT    LC3b_OWORD ;
      last_WriteTag       : OUT    LC3b_c_tag ;
      last_lru_data_in    : OUT    std_logic ;
      last_write0         : OUT    std_logic ;
      last_write1         : OUT    STD_LOGIC ;
      replace_way0        : OUT    std_logic ;
      replace_way1        : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Cache_Controller
   PORT (
      CLK                : IN     std_logic ;
      PMRESP_H           : IN     STD_LOGIC ;
      RESET_L            : IN     STD_LOGIC ;
      evict_buffer_valid : IN     std_logic ;
      miss               : IN     std_logic ;
      PMREAD_L           : OUT    STD_LOGIC ;
      PMWRITE_L          : OUT    STD_LOGIC ;
      in_idlehit         : OUT    std_logic ;
      in_load            : OUT    std_logic ;
      in_writeback       : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Comparator
   GENERIC (
      N     : Integer;
      Delay : time
   );
   PORT (
      A : IN     std_logic_vector (N-1 DOWNTO 0);
      B : IN     std_logic_vector (N-1 DOWNTO 0);
      Y : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT Stage2CacheLogic
   PORT (
      CLK                : IN     std_logic ;
      Dataout            : IN     LC3b_word ;
      Index              : IN     LC3b_C_INDEX ;
      MREAD_L            : IN     std_logic ;
      MWRITEH_L          : IN     std_logic ;
      MWRITEL_L          : IN     std_logic ;
      Offset             : IN     std_logic_vector (2 DOWNTO 0);
      PMDATAIN           : IN     LC3B_OWORD ;
      PMRESP_H           : IN     STD_LOGIC ;
      Tag                : IN     LC3b_C_TAG ;
      Way0Dataout        : IN     LC3B_OWORD ;
      Way1Dataout        : IN     LC3B_OWORD ;
      dirty0             : IN     std_logic ;
      dirty1             : IN     std_logic ;
      evicted            : IN     std_logic ;
      in_idlehit         : IN     std_logic ;
      in_load            : IN     std_logic ;
      in_writeback       : IN     std_logic ;
      index_match        : IN     STD_LOGIC ;
      last_Set_Dirty     : IN     std_logic ;
      last_WayDataIn     : IN     LC3b_OWORD ;
      last_WriteTag      : IN     LC3b_c_tag ;
      last_lru_data_in   : IN     std_logic ;
      last_write0        : IN     std_logic ;
      last_write1        : IN     STD_LOGIC ;
      replace_way0       : IN     std_logic ;
      replace_way1       : IN     std_logic ;
      tag0               : IN     LC3b_C_TAG ;
      tag1               : IN     LC3b_C_TAG ;
      valid0             : IN     std_logic ;
      valid1             : IN     std_logic ;
      DATAIN             : OUT    LC3b_word ;
      MRESP_H            : OUT    std_logic ;
      PMADDRESS          : OUT    LC3B_WORD ;
      PMDATAOUT          : OUT    LC3B_OWORD ;
      WayDataIn          : OUT    LC3b_OWORD ;
      WriteIndex         : OUT    LC3b_C_INDEX ;
      WriteTag           : OUT    LC3b_C_TAG ;
      evict_buffer_valid : OUT    std_logic ;
      lru_data_in        : OUT    STD_LOGIC ;
      set_dirty          : OUT    std_logic ;
      write0             : OUT    std_logic ;
      write1             : OUT    std_logic ;
      miss               : BUFFER std_logic 
   );
   END COMPONENT;
   COMPONENT AND2
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AND2 USE ENTITY mp3lib.AND2;
   FOR ALL : CacheFwdPipe USE ENTITY ece411.CacheFwdPipe;
   FOR ALL : Cache_Controller USE ENTITY ece411.Cache_Controller;
   FOR ALL : Comparator USE ENTITY ece411.Comparator;
   FOR ALL : Stage2CacheLogic USE ENTITY ece411.Stage2CacheLogic;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   aCacheFwdPipe : CacheFwdPipe
      PORT MAP (
         CLK                 => CLK,
         RESET_L             => RESET_L,
         WayDataIn           => WayDataIn,
         WriteTag            => WriteTag_internal,
         load_cache_fwd_pipe => load_cache_fwd_pipe,
         lru_data_in         => lru_data_in,
         next_index_match    => next_index_match,
         next_replace_way0   => next_replace_way0,
         next_replace_way1   => next_replace_way1,
         set_dirty           => set_dirty,
         write0              => write0,
         write1              => write1,
         index_match         => index_match,
         last_Set_Dirty      => last_Set_Dirty,
         last_WayDataIn      => last_WayDataIn,
         last_WriteTag       => last_WriteTag,
         last_lru_data_in    => last_lru_data_in,
         last_write0         => last_write0,
         last_write1         => last_write1,
         replace_way0        => replace_way0,
         replace_way1        => replace_way1
      );
   L1CacheController : Cache_Controller
      PORT MAP (
         CLK                => CLK,
         PMRESP_H           => PMRESP_H,
         RESET_L            => RESET_L,
         evict_buffer_valid => evict_buffer_valid,
         miss               => miss,
         PMREAD_L           => PMREAD_L,
         PMWRITE_L          => PMWRITE_L,
         in_idlehit         => in_idlehit,
         in_load            => in_load,
         in_writeback       => in_writeback
      );
   U_1 : Comparator
      GENERIC MAP (
         N     => 3,
         Delay => DELAY_COMPARE8
      )
      PORT MAP (
         A => Index,
         B => ReadIndex,
         Y => next_index_match
      );
   aCacheLogic : Stage2CacheLogic
      PORT MAP (
         CLK                => CLK,
         Dataout            => Dataout,
         Index              => Index,
         MREAD_L            => MREAD_L,
         MWRITEH_L          => MWRITEH_L,
         MWRITEL_L          => MWRITEL_L,
         Offset             => Offset,
         PMDATAIN           => PMDATAIN,
         PMRESP_H           => PMRESP_H,
         Tag                => Tag,
         Way0Dataout        => Way0Dataout,
         Way1Dataout        => Way1Dataout,
         dirty0             => dirty0,
         dirty1             => dirty1,
         evicted            => evicted,
         in_idlehit         => in_idlehit,
         in_load            => in_load,
         in_writeback       => in_writeback,
         index_match        => index_match,
         last_Set_Dirty     => last_Set_Dirty,
         last_WayDataIn     => last_WayDataIn,
         last_WriteTag      => last_WriteTag,
         last_lru_data_in   => last_lru_data_in,
         last_write0        => last_write0,
         last_write1        => last_write1,
         replace_way0       => replace_way0,
         replace_way1       => replace_way1,
         tag0               => tag0,
         tag1               => tag1,
         valid0             => valid0,
         valid1             => valid1,
         DATAIN             => DATAIN,
         MRESP_H            => MRESP_H,
         PMADDRESS          => PMADDRESS,
         PMDATAOUT          => PMDATAOUT,
         WayDataIn          => WayDataIn,
         WriteIndex         => WriteIndex,
         WriteTag           => WriteTag_internal,
         evict_buffer_valid => evict_buffer_valid,
         lru_data_in        => lru_data_in,
         set_dirty          => set_dirty,
         write0             => write0,
         write1             => write1,
         miss               => miss
      );
   U_2 : AND2
      PORT MAP (
         A => next_index_match,
         B => write0,
         F => next_replace_way0
      );
   U_3 : AND2
      PORT MAP (
         A => next_index_match,
         B => write1,
         F => next_replace_way1
      );

   -- Implicit buffered output assignments
   WriteTag <= WriteTag_internal;

END struct;
