-- VHDL Entity ece411.Predictor.interface
--
-- Created:
--          by - wheele11.ews (linux5.ews.illinois.edu)
--          at - 02:54:07 04/14/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Predictor IS
   PORT( 
      decode_btb_state          : IN     btb_line;
      decode_conditional        : IN     std_logic;
      decode_load_pc            : IN     std_logic;
      decode_pc                 : IN     lc3b_word;
      decode_prediction_correct : IN     STD_LOGIC;
      decode_taken              : IN     std_logic;
      decode_target_pc          : IN     lc3b_word;
      exec_btb_state            : IN     btb_line;
      exec_conditional          : IN     control_word;
      exec_load_pc              : IN     std_logic;
      exec_pc                   : IN     lc3b_word;
      exec_prediction_correct   : IN     std_logic;
      exec_taken                : IN     std_logic;
      exec_target_pc            : IN     LC3b_word;
      instr_addr                : IN     LC3b_word;
      mem_btb_state             : IN     btb_line;
      mem_conditional           : IN     std_logic;
      mem_load_pc               : IN     STD_LOGIC;
      mem_pc                    : IN     lc3b_word;
      mem_prediction_correct    : IN     std_logic;
      mem_taken                 : IN     std_logic;
      mem_target_pc             : IN     lc3b_word;
      target_pc_mux_sel         : IN     LC3B_4mux_sel;
      btb_state                 : OUT    btb_line;
      next_pc                   : OUT    LC3B_WORD
   );

-- Declarations

END Predictor ;

--
-- VHDL Architecture ece411.Predictor.struct
--
-- Created:
--          by - wheele11.ews (linux5.ews.illinois.edu)
--          at - 02:54:07 04/14/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY mp3lib;

ARCHITECTURE struct OF Predictor IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL two_16 : LC3B_WORD;


   -- Component Declarations
   COMPONENT ADD16
   PORT (
      A : IN     LC3B_WORD ;
      B : IN     LC3B_WORD ;
      F : OUT    LC3B_WORD 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ADD16 USE ENTITY mp3lib.ADD16;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   two_16 <= x"0002";


   -- Instance port mappings.
   U_0 : ADD16
      PORT MAP (
         A => instr_addr,
         B => two_16,
         F => next_pc
      );

END struct;
