-- VHDL Entity ece411.Splitter1.generatedInstance
--
-- Created:
--          by - goldste6.ews (gelib-057-19.ews.illinois.edu)
--          at - 20:44:33 04/15/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Splitter1 IS
   PORT( 
      Address : IN     LC3b_word;
      Index   : OUT    lc3b_c_index;
      Offset  : OUT    std_logic_vector (2 DOWNTO 0);
      Tag     : OUT    std_logic_vector (8 DOWNTO 0)
   );

END Splitter1 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Splitter1 IS 
BEGIN


END generatedInstance;
