-- VHDL Entity ece411.Splitter_L2.generatedInstance
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Splitter_L2 IS
   PORT( 
      Address : IN     LC3b_word;
      Index   : OUT    lc3b_l2_c_index;
      Offset  : OUT    LC3b_L2_C_Offset;
      Tag     : OUT    lc3b_l2_c_tag
   );

END Splitter_L2 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Splitter_L2 IS 
BEGIN


END generatedInstance;
