-- VHDL Entity ece411.uarch.generatedInstance
--
-- Created:
--          by - wheele11.ews (linux6.ews.illinois.edu)
--          at - 01:29:43 04/07/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY uarch IS
   PORT( 
      decode_control_out : IN     control_word;
      decode_data_out    : IN     pipe_data;
      uarch_sel_out      : OUT    STD_LOGIC;
      uarch_stall_out    : OUT    std_logic;
      uarch_control_out  : OUT    control_word;
      uarch_data_out     : OUT    pipe_data;
      CLK                : IN     std_logic
   );

END uarch ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF uarch IS 
BEGIN


END generatedInstance;
