-- VHDL Entity ece411.uarch_pipe.interface
--
-- Created:
--          by - wheele11.ews (gelib-057-28.ews.illinois.edu)
--          at - 21:51:11 04/08/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY uarch_pipe IS
   PORT( 
      CLK                   : IN     std_logic;
      RESET_L               : IN     STD_LOGIC;
      load_uarch_pipe       : IN     std_logic;
      uarch_control_out     : IN     control_word;
      uarch_data_out        : IN     pipe_data;
      uarch_sel_out         : IN     STD_LOGIC;
      uarch_stall_in_buffer : IN     std_logic;
      uarch_control_in      : OUT    control_word;
      uarch_data_in         : OUT    pipe_data;
      uarch_sel_in          : OUT    STD_LOGIC;
      uarch_stall_in        : OUT    std_logic
   );

-- Declarations

END uarch_pipe ;

--
-- VHDL Architecture ece411.uarch_pipe.struct
--
-- Created:
--          by - wheele11.ews (gelib-057-28.ews.illinois.edu)
--          at - 21:51:11 04/08/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;
LIBRARY mp3lib;

ARCHITECTURE struct OF uarch_pipe IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL F : STD_LOGIC;

   -- Implicit buffer signal declarations
   SIGNAL uarch_stall_in_internal : std_logic;


   -- Component Declarations
   COMPONENT RegControl
   PORT (
      RESET_L : IN     STD_LOGIC ;
      A       : IN     control_word ;
      EN      : IN     STD_LOGIC ;
      CLK     : IN     std_logic ;
      F       : OUT    control_word 
   );
   END COMPONENT;
   COMPONENT RegData
   PORT (
      RESET_L : IN     STD_LOGIC ;
      A       : IN     pipe_data ;
      EN      : IN     STD_LOGIC ;
      CLK     : IN     std_logic ;
      F       : OUT    pipe_data 
   );
   END COMPONENT;
   COMPONENT AND2
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT REG1
   PORT (
      RESET_L : IN     STD_LOGIC ;
      A       : IN     STD_LOGIC ;
      EN      : IN     STD_LOGIC ;
      CLK     : IN     STD_LOGIC ;
      F       : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AND2 USE ENTITY mp3lib.AND2;
   FOR ALL : REG1 USE ENTITY mp3lib.REG1;
   FOR ALL : RegControl USE ENTITY ece411.RegControl;
   FOR ALL : RegData USE ENTITY ece411.RegData;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   uarch_data_in <= uarch_data_out;


   -- Instance port mappings.
   U_1 : RegControl
      PORT MAP (
         RESET_L => RESET_L,
         A       => uarch_control_out,
         EN      => load_uarch_pipe,
         CLK     => CLK,
         F       => uarch_control_in
      );
   U_0 : RegData
      PORT MAP (
         RESET_L => RESET_L,
         A       => uarch_data_out,
         EN      => load_uarch_pipe,
         CLK     => CLK,
         F       => OPEN
      );
   U_4 : AND2
      PORT MAP (
         A => F,
         B => uarch_stall_in_internal,
         F => uarch_sel_in
      );
   U_2 : REG1
      PORT MAP (
         RESET_L => RESET_L,
         A       => uarch_sel_out,
         EN      => load_uarch_pipe,
         CLK     => CLK,
         F       => F
      );
   U_3 : REG1
      PORT MAP (
         RESET_L => RESET_L,
         A       => uarch_stall_in_buffer,
         EN      => load_uarch_pipe,
         CLK     => CLK,
         F       => uarch_stall_in_internal
      );

   -- Implicit buffered output assignments
   uarch_stall_in <= uarch_stall_in_internal;

END struct;
