-- VHDL Entity ece411.uop_mux.interface
--
-- Created:
--          by - wheele11.ews (linux5.ews.illinois.edu)
--          at - 23:16:01 04/06/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY uop_mux IS
   PORT( 
      CLK                    : IN     std_logic;
      decode_control_out     : IN     control_word;
      decode_data_out        : IN     pipe_data;
      uarch_control_in       : IN     control_word;
      uarch_data_in          : IN     pipe_data;
      uarch_sel_in           : IN     STD_LOGIC;
      decode_uop_control_out : OUT    control_word;
      decode_uop_data_out    : OUT    pipe_data
   );

-- Declarations

END uop_mux ;

--
-- VHDL Architecture ece411.uop_mux.struct
--
-- Created:
--          by - wheele11.ews (linux5.ews.illinois.edu)
--          at - 23:16:01 04/06/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF uop_mux IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT MUX2_ControlWord
   PORT (
      A   : IN     control_word ;
      B   : IN     control_word ;
      SEL : IN     STD_LOGIC ;
      F   : OUT    control_word 
   );
   END COMPONENT;
   COMPONENT Mux2_PipeData
   PORT (
      A   : IN     pipe_data ;
      B   : IN     pipe_data ;
      SEL : IN     STD_LOGIC ;
      F   : OUT    pipe_data 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : MUX2_ControlWord USE ENTITY ece411.MUX2_ControlWord;
   FOR ALL : Mux2_PipeData USE ENTITY ece411.Mux2_PipeData;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : MUX2_ControlWord
      PORT MAP (
         A   => decode_control_out,
         B   => uarch_control_in,
         SEL => uarch_sel_in,
         F   => decode_uop_control_out
      );
   U_1 : Mux2_PipeData
      PORT MAP (
         A   => decode_data_out,
         B   => uarch_data_in,
         SEL => uarch_sel_in,
         F   => decode_uop_data_out
      );

END struct;
