-- VHDL Entity ece411.wbStage.interface
--
-- Created:
--          by - wheele11.ews (linux5.ews.illinois.edu)
--          at - 01:04:21 04/08/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY wbStage IS
   PORT( 
      CLK           : IN     std_logic;
      wb_control    : IN     control_word;
      wb_control_in : IN     wb_control_word;
      wb_data_in    : IN     pipe_data;
      wb_instr      : IN     LC3b_word;
      wb_pc         : IN     LC3b_word
   );

-- Declarations

END wbStage ;

--
-- VHDL Architecture ece411.wbStage.struct
--
-- Created:
--          by - wheele11.ews (linux5.ews.illinois.edu)
--          at - 01:04:21 04/08/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF wbStage IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- Instance port mappings.

END struct;
