echo "--- Executing initialization force file for ../testcode/btbloop.asm ---"

echo "Resetting processor for 5 ns."
force /reset_l 0 @0
force /reset_l 1 @5
echo "Initializing the processor."
force /start_h 0 @0
force /start_h 1 @10

-- Test case: lowering start_h should not impact the function of the processor
force /start_h 0 @ 100

echo "Done initializing processor, loading ../testcode/btbloop.asm program code."
run 5
change /cpu/dram/phys_mem/vhdl_memory/mem(0) X"1C"
change /cpu/dram/phys_mem/vhdl_memory/mem(1) X"E0"
change /cpu/dram/phys_mem/vhdl_memory/mem(2) X"61"
change /cpu/dram/phys_mem/vhdl_memory/mem(3) X"12"
change /cpu/dram/phys_mem/vhdl_memory/mem(4) X"A2"
change /cpu/dram/phys_mem/vhdl_memory/mem(5) X"14"
change /cpu/dram/phys_mem/vhdl_memory/mem(6) X"01"
change /cpu/dram/phys_mem/vhdl_memory/mem(7) X"02"
change /cpu/dram/phys_mem/vhdl_memory/mem(8) X"17"
change /cpu/dram/phys_mem/vhdl_memory/mem(9) X"08"
change /cpu/dram/phys_mem/vhdl_memory/mem(10) X"7F"
change /cpu/dram/phys_mem/vhdl_memory/mem(11) X"12"
change /cpu/dram/phys_mem/vhdl_memory/mem(12) X"BE"
change /cpu/dram/phys_mem/vhdl_memory/mem(13) X"14"
change /cpu/dram/phys_mem/vhdl_memory/mem(14) X"04"
change /cpu/dram/phys_mem/vhdl_memory/mem(15) X"66"
change /cpu/dram/phys_mem/vhdl_memory/mem(16) X"13"
change /cpu/dram/phys_mem/vhdl_memory/mem(17) X"08"
change /cpu/dram/phys_mem/vhdl_memory/mem(18) X"C0"
change /cpu/dram/phys_mem/vhdl_memory/mem(19) X"40"
change /cpu/dram/phys_mem/vhdl_memory/mem(20) X"7F"
change /cpu/dram/phys_mem/vhdl_memory/mem(21) X"12"
change /cpu/dram/phys_mem/vhdl_memory/mem(22) X"1D"
change /cpu/dram/phys_mem/vhdl_memory/mem(23) X"02"
change /cpu/dram/phys_mem/vhdl_memory/mem(24) X"1E"
change /cpu/dram/phys_mem/vhdl_memory/mem(25) X"02"
change /cpu/dram/phys_mem/vhdl_memory/mem(26) X"1F"
change /cpu/dram/phys_mem/vhdl_memory/mem(27) X"02"
change /cpu/dram/phys_mem/vhdl_memory/mem(28) X"20"
change /cpu/dram/phys_mem/vhdl_memory/mem(29) X"02"
change /cpu/dram/phys_mem/vhdl_memory/mem(30) X"21"
change /cpu/dram/phys_mem/vhdl_memory/mem(31) X"02"
change /cpu/dram/phys_mem/vhdl_memory/mem(32) X"22"
change /cpu/dram/phys_mem/vhdl_memory/mem(33) X"02"
change /cpu/dram/phys_mem/vhdl_memory/mem(34) X"23"
change /cpu/dram/phys_mem/vhdl_memory/mem(35) X"02"
change /cpu/dram/phys_mem/vhdl_memory/mem(36) X"24"
change /cpu/dram/phys_mem/vhdl_memory/mem(37) X"02"
change /cpu/dram/phys_mem/vhdl_memory/mem(38) X"61"
change /cpu/dram/phys_mem/vhdl_memory/mem(39) X"12"
change /cpu/dram/phys_mem/vhdl_memory/mem(40) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(41) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(42) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(43) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(44) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(45) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(46) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(47) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(48) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(49) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(50) X"C3"
change /cpu/dram/phys_mem/vhdl_memory/mem(51) X"1E"
change /cpu/dram/phys_mem/vhdl_memory/mem(52) X"02"
change /cpu/dram/phys_mem/vhdl_memory/mem(53) X"6C"
change /cpu/dram/phys_mem/vhdl_memory/mem(54) X"C3"
change /cpu/dram/phys_mem/vhdl_memory/mem(55) X"10"
change /cpu/dram/phys_mem/vhdl_memory/mem(56) X"FF"
change /cpu/dram/phys_mem/vhdl_memory/mem(57) X"0F"
change /cpu/dram/phys_mem/vhdl_memory/mem(58) X"3C"
change /cpu/dram/phys_mem/vhdl_memory/mem(59) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(60) X"03"
change /cpu/dram/phys_mem/vhdl_memory/mem(61) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(62) X"0D"
change /cpu/dram/phys_mem/vhdl_memory/mem(63) X"60"
change /cpu/dram/phys_mem/vhdl_memory/mem(64) X"AD"
change /cpu/dram/phys_mem/vhdl_memory/mem(65) X"BA"
change /cpu/dram/phys_mem/vhdl_memory/mem(66) X"4E"
change /cpu/dram/phys_mem/vhdl_memory/mem(67) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(68) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(69) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(70) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(71) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(72) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(73) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(74) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(75) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(76) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(77) X"00"
change /cpu/dram/phys_mem/vhdl_memory/mem(78) X"41"
change /cpu/dram/phys_mem/vhdl_memory/mem(79) X"16"
change /cpu/dram/phys_mem/vhdl_memory/mem(80) X"C0"
change /cpu/dram/phys_mem/vhdl_memory/mem(81) X"C1"
change /cpu/dram/phys_mem/vhdl_memory/mem(82) X"03"
change /cpu/dram/phys_mem/vhdl_memory/mem(83) X"6C"
change /cpu/dram/phys_mem/vhdl_memory/mem(84) X"F1"
change /cpu/dram/phys_mem/vhdl_memory/mem(85) X"0F"
change /cpu/dram/phys_mem/vhdl_memory/mem(86) X"03"
change /cpu/dram/phys_mem/vhdl_memory/mem(87) X"6C"
change /cpu/dram/phys_mem/vhdl_memory/mem(88) X"EF"
change /cpu/dram/phys_mem/vhdl_memory/mem(89) X"0F"
change /cpu/dram/phys_mem/vhdl_memory/mem(90) X"03"
change /cpu/dram/phys_mem/vhdl_memory/mem(91) X"6C"
change /cpu/dram/phys_mem/vhdl_memory/mem(92) X"ED"
change /cpu/dram/phys_mem/vhdl_memory/mem(93) X"0F"
change /cpu/dram/phys_mem/vhdl_memory/mem(94) X"03"
change /cpu/dram/phys_mem/vhdl_memory/mem(95) X"6C"
change /cpu/dram/phys_mem/vhdl_memory/mem(96) X"EB"
change /cpu/dram/phys_mem/vhdl_memory/mem(97) X"0F"
change /cpu/dram/phys_mem/vhdl_memory/mem(98) X"03"
change /cpu/dram/phys_mem/vhdl_memory/mem(99) X"6C"
change /cpu/dram/phys_mem/vhdl_memory/mem(100) X"E9"
change /cpu/dram/phys_mem/vhdl_memory/mem(101) X"0F"
change /cpu/dram/phys_mem/vhdl_memory/mem(102) X"03"
change /cpu/dram/phys_mem/vhdl_memory/mem(103) X"6C"
change /cpu/dram/phys_mem/vhdl_memory/mem(104) X"E7"
change /cpu/dram/phys_mem/vhdl_memory/mem(105) X"0F"
change /cpu/dram/phys_mem/vhdl_memory/mem(106) X"03"
change /cpu/dram/phys_mem/vhdl_memory/mem(107) X"6C"
change /cpu/dram/phys_mem/vhdl_memory/mem(108) X"E5"
change /cpu/dram/phys_mem/vhdl_memory/mem(109) X"0F"
change /cpu/dram/phys_mem/vhdl_memory/mem(110) X"03"
change /cpu/dram/phys_mem/vhdl_memory/mem(111) X"6C"
change /cpu/dram/phys_mem/vhdl_memory/mem(112) X"E3"
change /cpu/dram/phys_mem/vhdl_memory/mem(113) X"0F"
run 5
echo "Done loading ../testcode/btbloop.asm program code."
